### ISSUE TITLE
Unable to get it working on Authentik

### ISSUE THREAD

**Issue by AlessandroSechi** [Timshel/vaultwarden#2]
Hello, I'm trying to have SSO working in my home setup with Authentik.
Configuration looks like:
![image](https://github.com/Timshel/vaultwarden/assets/15678855/66426d21-071d-4963-b1d4-edfdee3e9793)

But I get error when attempting to login via SSO
`{"ErrorModel":{"Message":"Failed to discover OpenID provider: Failed to parse server response","Object":"error"},"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null,"Message":"Failed to discover OpenID provider: Failed to parse server response","Object":"error","ValidationErrors":{"":["Failed to discover OpenID provider: Failed to parse server response"]},"error":"","error_description":""}`

Vaultwarden debug logs:

```
vaultwarden  | [2023-10-07 11:49:32.313][reqwest::connect][DEBUG] starting new connection: https:///
vaultwarden  | [2023-10-07 11:49:32.313][trust_dns_proto::xfer::dns_handle][DEBUG] querying: my.authentik.com A
vaultwarden  | [2023-10-07 11:49:32.313][trust_dns_resolver::name_server::name_server_pool][DEBUG] sending request: [Query { name: Name("my.authentik.com"), query_type: A, query_class: IN }]
vaultwarden  | [2023-10-07 11:49:32.313][trust_dns_resolver::name_server::name_server][DEBUG] reconnecting: NameServerConfig { socket_addr: 127.0.0.11:53, protocol: Udp, tls_dns_name: None, trust_nx_responses: false, bind_addr: None }
vaultwarden  | [2023-10-07 11:49:32.314][trust_dns_proto::xfer][DEBUG] enqueueing message:QUERY:[Query { name: Name("my.authentik.com"), query_type: A, query_class: IN }]
vaultwarden  | [2023-10-07 11:49:32.314][trust_dns_proto::udp::udp_client_stream][DEBUG] final message: ; header 25315:QUERY:RD:NoError:QUERY:0/0/0
vaultwarden  | ; query
vaultwarden  | ;; my.authentik.com. IN A
vaultwarden  |
vaultwarden  | [2023-10-07 11:49:32.314][trust_dns_proto::udp::udp_stream][DEBUG] created socket successfully
vaultwarden  | [2023-10-07 11:49:32.315][trust_dns_proto::udp::udp_client_stream][DEBUG] received message id: 25315
vaultwarden  | [2023-10-07 11:49:32.315][trust_dns_resolver::error][DEBUG] Response:; header 25315:RESPONSE:RD,RA:NoError:QUERY:1/0/0
vaultwarden  | ; query
vaultwarden  | ;; my.authentik.com. IN A
vaultwarden  | ; answers 1
vaultwarden  | my.authentik.com. 489 IN A 10.10.10.10
vaultwarden  | ; nameservers 0
vaultwarden  | ; additionals 0
vaultwarden  |
vaultwarden  | [2023-10-07 11:49:32.315][trust_dns_resolver::error][DEBUG] Response:; header 25315:RESPONSE:RD,RA:NoError:QUERY:1/0/0
vaultwarden  | ; query
vaultwarden  | ;; my.authentik.com. IN A
vaultwarden  | ; answers 1
vaultwarden  | my.authentik.com. 489 IN A 10.10.10.10
vaultwarden  | ; nameservers 0
vaultwarden  | ; additionals 0
vaultwarden  |
vaultwarden  | [2023-10-07 11:49:32.324][h2::client][DEBUG] binding client connection
vaultwarden  | [2023-10-07 11:49:32.324][h2::client][DEBUG] client connection bound
vaultwarden  | [2023-10-07 11:49:32.324][h2::codec::framed_write][DEBUG] send frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
vaultwarden  | [2023-10-07 11:49:32.324][h2::proto::connection][DEBUG] Connection; peer=Client
vaultwarden  | [2023-10-07 11:49:32.324][h2::codec::framed_write][DEBUG] send frame=WindowUpdate { stream_id: StreamId(0), size_increment: 5177345 }
vaultwarden  | [2023-10-07 11:49:32.324][h2::codec::framed_write][DEBUG] send frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }
vaultwarden  | [2023-10-07 11:49:32.325][h2::codec::framed_read][DEBUG] received frame=Settings { flags: (0x0), max_concurrent_streams: 128, initial_window_size: 65536, max_frame_size: 16777215 }
vaultwarden  | [2023-10-07 11:49:32.325][h2::codec::framed_write][DEBUG] send frame=Settings { flags: (0x1: ACK) }
vaultwarden  | [2023-10-07 11:49:32.325][h2::codec::framed_read][DEBUG] received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 2147418112 }
vaultwarden  | [2023-10-07 11:49:32.325][h2::codec::framed_read][DEBUG] received frame=Settings { flags: (0x1: ACK) }
vaultwarden  | [2023-10-07 11:49:32.325][h2::proto::settings][DEBUG] received settings ACK; applying Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
vaultwarden  | [2023-10-07 11:49:32.356][h2::codec::framed_read][DEBUG] received frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
vaultwarden  | [2023-10-07 11:49:32.356][h2::codec::framed_read][DEBUG] received frame=Data { stream_id: StreamId(1), flags: (0x1: END_STREAM) }
vaultwarden  | [2023-10-07 11:49:32.356][trust_dns_proto::xfer::dns_exchange][DEBUG] io_stream is done, shutting down
vaultwarden  | [2023-10-07 11:49:32.356][vaultwarden::sso][ERROR] Failed to discover OpenID provider: Failed to parse server response
vaultwarden  | [2023-10-07 11:49:32.356][h2::codec::framed_write][DEBUG] send frame=GoAway { error_code: NO_ERROR, last_stream_id: StreamId(0) }
vaultwarden  | [2023-10-07 11:49:32.356][h2::proto::connection][DEBUG] Connection::poll; connection error error=GoAway(b"", NO_ERROR, Library)
vaultwarden  | [2023-10-07 11:49:32.357][response][INFO] (authorize) GET /identity/connect/authorize?<data..> => 400 Bad Request
vaultwarden  | [2023-10-07 11:49:32.543][request][INFO] GET /favicon.ico
vaultwarden  | [2023-10-07 11:49:32.543][response][INFO] (web_files) GET /<p..> [10] => 200 OK
vaultwarden  | [2023-10-07 11:49:35.796][vaultwarden::api::core::two_factor][DEBUG] Sending notifications for incomplete 2FA logins
vaultwarden  | [2023-10-07 11:49:35.796][vaultwarden::api::core::accounts][DEBUG] Purging auth requests
vaultwarden  | [2023-10-07 11:49:35.842][request][INFO] GET /alive
vaultwarden  | [2023-10-07 11:49:35.842][response][INFO] (alive) GET /alive => 200 OK
vaultwarden  | [2023-10-07 11:50:35.798][vaultwarden::api::core::two_factor][DEBUG] Sending notifications for incomplete 2FA logins
vaultwarden  | [2023-10-07 11:50:35.798][vaultwarden::api::core::accounts][DEBUG] Purging auth requests
```

**Comment by Timshel** [comment]
Hey,
First  of all sorry I missed the issue, will have to search why I had no notification :(.
Ok so the `Failed to discover OpenID provider` come from an error in parsing the openid discovery endpoint.
 
Note the `SSO_AUTHORITY` does not need to include `.well-known/openid-configuration` part.

For example for Gitlab :
 - endpoint is https://gitlab.com/.well-known/openid-configuration
 - parameter is `SSO_AUTHORITY=https://gitlab.com`

**Comment by AlessandroSechi** [comment]
Hi, thank you for your time. 

> Maybe drop the trailing / ?

Dropping the trailing /, produces weird error according to configuration:
```
{"ErrorModel":{"Message":"Failed to discover OpenID provider: Validation error: unexpected issuer URI `https://my.authentik.com/application/o/vaultwarden/` (expected `https://my.authentik.com/application/o/vaultwarden`)","Object":"error"},"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null,"Message":"Failed to discover OpenID provider: Validation error: unexpected issuer URI `https://my.authentik.com/application/o/vaultwarden/` (expected `https://my.authentik.com/application/o/vaultwarden`)","Object":"error","ValidationErrors":{"":["Failed to discover OpenID provider: Validation error: unexpected issuer URI `https://my.authentik.com/application/o/vaultwarden/` (expected `https://my.authentik.com/application/o/vaultwarden`)"]},"error":"","error_description":""}
```

![image](https://github.com/Timshel/vaultwarden/assets/15678855/e5a6e864-1ecd-4c28-ac6c-2749f25c6309)


In the meantime, I'll create the dump for you

**Comment by AlessandroSechi** [comment]
Ok @Timshel, I prepared kindof minimum reproducible example:

docker-compose.yml

```
---
version: "3.4"

services:
  postgresql:
    image: docker.io/library/postgres:12-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - .env
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.8.3}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_BOOTSTRAP_PASSWORD: password
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      - postgresql
      - redis
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2023.8.3}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_BOOTSTRAP_PASSWORD: password
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis
  vaultwarden:
    image: local.registry/vaultwarden:1.0
    container_name: vaultwarden
    restart: unless-stopped
    ports:
     - 127.0.0.1:9445:80 #map any custom port to use (replace 8445 not 80)
    volumes:
     - ./bitwarden:/data:rw
    environment:
     - ADMIN_TOKEN=admin
     - WEBSOCKET_ENABLED=true
     - SSO_ENABLED=true
     - DOMAIN=http://localhost
     - LOG_LEVEL=debug
     - SSO_CLIENT_ID=71lsSaIxaxeLt2gSLVbA1BGAMUnOSXLsvcstqzxB
     - SSO_CLIENT_SECRET=i28vPTHDzsoJrxLv6T3E0M3dnsgtjaug4OgX1mJuusnhxMe1jINzsSxD6jt3u5OmMcMFy6ZsdyMwhUMC23c7qvq5RLfJPtGjEhWKBqa31zfo2e1IVIbAXc4ObOHCEMv0
     - SSO_AUTHORITY=http://localhost:9000/application/o/vaultwarden/
    logging:
      options:
        max-size: 1G

volumes:
  database:
    driver: local
  redis:
    driver: local
```

Then

```
export PG_PASS=4JTT186LwxjpVyoIv4oH8gBUL0y7e1IdUHz8vcZB
export AUTHENTIK_SECRET_KEY=Sva7GzefVvwxkqNVDeDKJeRVbHVmLKg91yVHpFRIr9XWSSOYEz
export AUTHENTIK_POSTGRESQL__PASSWORD=4JTT186LwxjpVyoIv4oH8gBUL0y7e1IdUHz8vcZB

docker compose up -d
```

Authentik user details:

username: akadmin
password: password
email: root@example.com
